version: '3.2'

services:
  mysql:
    image: mysql
    expose:
      - '3306'
    ports:
      - '3306:3306'
    volumes:
      - mysqlCalendar:/var/lib/mysql
      #- ./mysql_init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'calendar'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'

volumes:
  mysqlCalendar:

